### ISSUE TITLE
shaman totem getting aggro on itself

### ISSUE THREAD

**Issue by Tikomius** [dalaranwow/issue-tracker#10]
/magma totem getting aggro on itself if does damage more than me/
/totem aggro removed in 3.0.8 patch/

https://wowwiki-archive.fandom.com/wiki/Magma_Totem

i have to scale down magma totem for it to not get destroyed, 1 fire nova isnt enough to hold aggro on myself.

![Screenshot 08-24-2022 19 46 16](https://user-images.githubusercontent.com/111995251/186449250-be891be5-4764-4449-8087-df677ccd0092.png)

 it is destroyed within 5-6 second after i did: magma totem->fire nova. im new to the bugtracker cant post recording here.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, this has been fixed and it will be available in the live realm after the next maintenance.

**Comment by Tikomius** [comment]
thank you very much, will wait wholeheartly.
