### ISSUE TITLE
Pet focus is resetting to zero when player mounts(this is a HUGE handicap for PvP)

### ISSUE THREAD

**Issue by slicplaya** [dalaranwow/issue-tracker#11]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: Pet focus is resetting to zero when player mounts(this is a HUGE handicap for PvP). This is also happening when dismissing the pet. So your scripting has pets resetting or refreshing with a default of 0 focus. This is not correct.

**Expected behaviour**: Pet focus should not snapshot, but continue to regen to 100 when mounted.

**Steps to reproduce the problem**:

1. player dismounts, pet focus raises to 100
2. mount up on any mount
3. dismount and see the focus reset to 0-1

**Include proofs**
![image](https://user-images.githubusercontent.com/6567001/186601811-22e6ecde-f3af-4351-93b4-a12783a27faa.png)
![image](https://user-images.githubusercontent.com/6567001/186601973-6c074c60-71c9-42fd-880a-f0a1aa8a7265.png)

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, it is greatly appreciated. This issue has been fixed and it will be in the live realm after the next maintenance.
