### ISSUE TITLE
[Quest] Facing Negolash Unavailable

### ISSUE THREAD

**Issue by SkinHeadBaby** [dalaranwow/issue-tracker#19]
**Current behaviour**: 
After completing the quests [The Monogrammed Sash] and [The Captains's Chest] i cant take the next quest in the chain [The Captain's Cutlass] or the following one [Facing Negolash].
Also the item "The Monogrammed Sash" drops every time you kill Mok'rash the giant at the island in booty bay where the goblin statue is and lets to take and complete the quest repeatedly for experience and reputation rewards.

**Expected behaviour**: 
Its expected to be able to complete the quests once and then be able to accept the next quest in the chain.

**Steps to reproduce the problem**:

1. Take the quests.
2. Complete the objectives.
3. Turn in the quests.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report. It will be fixed after the next maintenance.

**Comment by SkinHeadBaby** [comment]
I can confirm after the last restart turning in the quest [The Monogrammed Sash] gave me the next quest to talk to the [NPC] Sprogger who acctually gave me the quest [Facing Negolash],
but the sub quest [Enticing Negolash] is not available at the boat wreck east from booty bay where you give buzzard wings and juglevine wine to spawn Negolash
![Untitled](https://user-images.githubusercontent.com/12463364/187956517-a935cf08-12e9-4bc9-b52c-c2debd4013be.png)
