### ISSUE TITLE
Fleeing behaviour

### ISSUE THREAD

**Issue by ghost** [dalaranwow/issue-tracker#2]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: Fleeing behaviour doesn't work, NPCs who should flee on low health, doesn't do it and will fight to end instead.

**Expected behaviour**: NPCs should try flee on low health, and not fight to the end.

**Steps to reproduce the problem**:

Venture Co. Gemologist (lvl 6-7)
Venture Co. Saboteur (lvl 6-7)

These NPCs are on Azuremyst Isle, fight with one of them. You notice when they are on low health, they won't flee and trying to get help from other NPCs around camp, but will fight to end instead.

This was just one example, but many other NPCs (humanoids, beasts etc) also have fleeing behaviour.

**Include the ID for the gameobjects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, achievements, skills**

https://www.wowhead.com/wotlk/npc=17279/venture-co-gemologist

https://www.wowhead.com/wotlk/npc=17278/venture-co-saboteur

https://wowpedia.fandom.com/wiki/Runner

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, I will look into it. After a quick test it does certainly seem odd, so appreciated the report. Merging #3  with this one. I will work on both of them.

**Comment by Lothloryen** [comment]
Hello again,

This and #3 are now fixed, they will be active in Dalaran realm after the next maintenance.
