### ISSUE TITLE
[Spell=34477] Hunter misdirection spell goes on permanent cooldown

### ISSUE THREAD

**Issue by PotemkinBuster** [dalaranwow/issue-tracker#24]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail, please.
Occasionally hunters misdirection spell will go on permanent cooldown. 

This is the macro I am using:
#showtooltip Misdirection
/cast [target=Spirit Beast] Misdirection

I usually spam the macro, I am unsure if this affects the spell in any way. Relogging seems to be the only solution to the issue.

**Expected behaviour**: Tell us what should happen instead.
Misdirection should incur a 30 second cooldown

**Steps to reproduce the problem**:

1. Cast misdirection macro stated above
2. Upon misdirection expiring the skill will not go on cooldown
3. Misdirection stays greyed 

**Include proofs**
https://imgur.com/iXyEY4V

You can research about the corect behaviour on several sites like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/ or similars.
Issues without proofs may be closed or put on hold until evidence is provided.

**Include the ID for the gameobjects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, achievements, skills**

You can find this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots if you have any, please**

**Comment by slicplaya** [comment]
I was unable to duplicate this. Mine worked 100% fine on multiple occasions. Try this macro. If you have a focus, it'll cast at the focus. If no focus, it goes to pet. Happy hunting!!

#showtooltip Misdirection
/cast [@focus,help][help][@pet,exists] Misdirection

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, I have done a quick fix for this that will also improve the behaviour from a few other spells. It looks fine on all my tests - but please, let me know if this issue persists after the fix goes live (next maintenance, which should happen in ~45 minutes).
