### ISSUE TITLE
Venture Co. Saboteur "Torch Burn" ability missing

### ISSUE THREAD

**Issue by ghost** [dalaranwow/issue-tracker#3]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: Venture Co. Saboteur should have ability called "Torch Burn", which has 35% to proc on melee attacks against enemy, causes fire damage.

But it doesn't seem to proc at all, it should happen pretty often with 35% chance.

**Expected behaviour**: "Torch Burn" ability on Venture Co. Saboteur should proc on melee attacks, with 35% chance to happen.

**Steps to reproduce the problem**:

Fight with NPC Venture Co. Saboteur on Azuremyst Isle, "Torch Burn" ability should activate any time during fight with this NPC, when ability procs it causes fire animation on player, but ability seems to never proc even it does have 35% chance to happen on each melee attack Venture Co. Saboteur does.

**Include the ID for the gameobjects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, achievements, skills**

https://www.wowhead.com/wotlk/npc=17278/venture-co-saboteur

https://www.wowhead.com/wotlk/spell=5680/torch-burn

https://www.wowhead.com/wotlk/spell=5679/torch-burn

**Comment by Lothloryen** [comment]
#2
