### ISSUE TITLE
NPC's as WELL as Player Pets clip and fall through walls/mountains/terrain

### ISSUE THREAD

**Issue by slicplaya** [dalaranwow/issue-tracker#32]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: NPC's as WELL as Player Pets clip and fall through walls/mountains/terrain. It's insanely annoying expecially when trying to fight/kite a mob or turn in a quest and the mob just falls and resets or bugs out, or the NPC is unreachable.

**Expected behaviour**: NPC's and player pets should respec the invisible walls of terrain.

**Comment by slicplaya** [comment]
![WoWScrnShot_090522_093511](https://user-images.githubusercontent.com/6567001/188490187-eb08a019-275e-4002-9972-4e707a738f0e.jpg)

**Comment by Lothloryen** [comment]
Thank you, related to #5
