### ISSUE TITLE
Amanitar fight is bugged and is also immune to Serpent Sting(Nature Damage)

### ISSUE THREAD

**Issue by slicplaya** [dalaranwow/issue-tracker#34]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behavior**: Amanitar is immune to Serpent Sting in Old Kingdom. This effectively makes a MM hunter absolutely useless for the fight. The same goes for Ionar in Halls of Lightning. These elementals should not have values of immunity to elements just for the sheer fact of negating an entire class. It's a very common issue on private servers until fixed.
Another issue during the fight, destroying a healthy mushroom while not under the de-buff mini should give the player a "Potent Fungus" buff for the fight unless mini is cast which removes the buff if a player has it or makes u mini if player is in a normal state.

**Expected behavior**: Serpent sting and other elemental attacks/spells should effectively hit the bosses as to not negate entire classes such as elemental shamans or MM hunters.

**Steps to reproduce the problem**:

1. make a hunter.
2. cast serpent sting on either boss
3. Notice it says immune
4. Destroy a healthy mushroom while in a normal state
5. See that the Potent Fungus buff for 100% damage doesn't work
6. Say wtf, why, and report it 

**Include proofs**
https://wowwiki-archive.fandom.com/wiki/Amanitar

**Include Screenshots**
![WoWScrnShot_090822_010658](https://user-images.githubusercontent.com/6567001/189070816-0b8972a1-d7ee-41d4-9b2a-172787c908da.jpg)
![WoWScrnShot_090822_011748](https://user-images.githubusercontent.com/6567001/189072079-09646036-187a-4198-9e54-3a9db6c0dd48.jpg)
![WoWScrnShot_090822_011756](https://user-images.githubusercontent.com/6567001/189072082-8fe5172e-fc7d-40de-98ac-03206615656d.jpg)

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, I will be taking a look to check if Amanitar should have nature immunity, appreciated the heads up.

Regarding the Mushrooms, they work as intended - the thing is, in order for the to have effect on you, you must be nearby, else you will not receive it.

**Comment by slicplaya** [comment]
I killed 4 mushrooms at the start with no buff before Mini was cast. Directly on top of the mushroom with a melee attack as you have to be super close to it.
