### ISSUE TITLE
Prince Taldaram Fire Orbs hit way too often

### ISSUE THREAD

**Issue by slicplaya** [dalaranwow/issue-tracker#35]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behavior**: Currently, the orbs hit rapidly either 2-3x faster than they should be scripted for. Even with Fire res aura/totem, a single orb can destroy the entire party in about 3-5 seconds.

**Expected behavior**: They should hit half as often.

**Steps to reproduce the problem**:

1. Jump on the test server and look.

**Comment by Lothloryen** [comment]
Hello there,

Thank you again for the reports. The values that the spheres have are exactly these: https://www.wowhead.com/spell=55926/flame-sphere-periodic (200ms) so the periodic cast is correctly scripted, the same goes to the damage values from the sear beam. Nonetheless, if it is causing issues to some parties, I will be checking it thoroughly, just in case.

**Comment by slicplaya** [comment]
Copy that
