### ISSUE TITLE
Logging out/alt f4ing in RDF dungeon kicks you from the group upon returning

### ISSUE THREAD

**Issue by slicplaya** [dalaranwow/issue-tracker#4]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behavior**: Logging out/alt f4ing in RDF dungeon kicks you from the group upon returning.

**Expected behavior**: You should not be kicked or removed from the group for re-logging or dcing, so that when you return, you're still in the group and can acquire the rdf satchel. I was re-invited by the party leader of RDF which is a whole nother problem in itself since you're locked into an RDF group. Upon completion of dungeon, I did not receive my satchel. This is a bug.

**Steps to reproduce the problem**:

1. join an RDF group
2. alt f4 or re log
3. find out that you've been removed from the group for re-logging.

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for the report.

It should be fixed, it will go live to Dalaran realm after the next maintenance.

**Comment by slicplaya** [comment]
As a point of note, it stops the exp gain and satchel for EVERYONE in group, and disallows re queuing for RDF. AND teleports players to nearest Graveyard even if it's not their own faction upon leaving group.

**Comment by Lothloryen** [comment]
Greetings,

Yes, thank you. The fix also considered that, so it should be fine now.
