### ISSUE TITLE
[Druid] Shapeshifting with ! macro not always breaking roots

### ISSUE THREAD

**Issue by phonkala** [dalaranwow/issue-tracker#44]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: For some reason, using shapeshifting macros like /cast !Cat Form does not break roots correctly. Currently it feels like using such a macro for hunter aspects (if you are already in certain aspect, it won't cast it again if using ! macro). This should not be the case with druid forms.

**Expected behaviour**: Using macros like /cast !Cat Form should break roots identically to manually shapeshifting out of form and back into Cat form (and all other forms).

**Steps to reproduce the problem**:

One of many examples I've found:

1. Make a Druid shapeshifting macro like /cast !Cat Form
2. Go to Nexus last boss Keristraza and get it to cast Crystal Chains on you.
3. Use the macro -> It won't break the roots as it should.
4. Manually cancel your animal form -> roots do break.
-> Behaviour of using the macro and manually swapping out of form should be identical.

**Include proofs**

Well this one is quite widely know, I believe in pretty much any video of Druids in battlegrounds, dungeons etc from 2008+, you can see people using such macros to successfully break roots. This is the first server I see it not working, ever. It is hugely essential part of druids too, would love a quick fix.

**Comment by phonkala** [comment]
Just to be a little bit more specific, the shapeshifting (including with ! macros) should remove most **movement-impairing effects**, not just roots. I can remember I had same issue with few slow effects, but can't remember exactly what they were.

Couldn't find better written proof of this than a wowpedia article from 2012, but it is shown even then this is the way it should work even shapeshifting was nerfed in Cata.
https://wowpedia.fandom.com/wiki/Druid_shapeshift_forms?oldid=2951927

**Comment by phonkala** [comment]
Been trying to remember to check this whenever I get rooted and to be honest, it seems like roots or slows etc are NEVER broken when using the !<formname> macros. At least what I have been able to test it on npcs that cast roots, or in Wintergrasp by enemy players, it's just not working correctly. Manually swapping to caster form and back to animal form works. This is a HUGE issue to druids, as probably most know druids are the masters of escaping roots and slows just by and especially using these macros.

**Comment by phonkala** [comment]
Finally found also proof, video of feral pvp from 2009:
https://www.youtube.com/watch?v=EqLPKtBlOmw&t=58s

No trinket or other cooldowns used, feral just clears freeze by recasting Cat form, never going into caster form (obviously using ! macro, as it would not be possible otherwise to not go into caster form).

Also, there are already plenty druid videos from Classic WotLK where people escape roots/slows using !form macros, never going into caster form.

**Comment by phonkala** [comment]
More proof: https://www.youtube.com/watch?v=WsZjTVcQyWw

This really needs to be fixed quickly, its completely destroying druid pvp and also affecting many pve situations.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report. I have been doing some tests, and the Cat Form powershifting with `!` macros seems to work just fine in PvP against roots, freezes, earthbind totem etc (`!/cast Cat Form`). I will do some tests in PvE but, for now seems to be working properly with every kind of snare effect. If you could provide a way to reproduce it in PvP, I will gladly take a look.

It seems to not be working specifically with the Tree of Life form, which I have already fixed and will be deployed with the next maintenance.

Thank you very much.

**Comment by phonkala** [comment]
Good job on this one, finally I feel like a druid again! :) Yes I was playing mostly resto druid, I remember testing these issues at first with tree form and cat form, but then later just used tree form as I though they must be connected.

There are still some random issues with this: for example, in Culling of Stratholme there are NPCs called Acolyte (https://www.wowhead.com/wotlk/npc=27731/acolyte#abilities;mode:heroic) that use the spell Cone of Cold (https://www.wowhead.com/wotlk/spell=15244/cone-of-cold). For some reason, using the ! macros (at least in tree form) after being hit by the cone of cold does not remove the slow.
