### ISSUE TITLE
Spell - 4 piece tier 8 mage set bonus not working

### ISSUE THREAD

**Issue by selfsim** [dalaranwow/issue-tracker#61]
**Current behaviour**: 4 piece T8 mage set bonus is not procing at all for fire or arcane.

**Expected behaviour**: With some probability > 0, missile barrage and hot streak should not be consumed when arcane missiles or pyroblast are cast, respectively.

**Steps to reproduce the problem**:

1. Test mage 4pt8 against training dummies

https://www.wowhead.com/wotlk/spell=64869/item-mage-t8-4p-bonus

Here is a discussion about the issue on the Sunwell PS. In the discussion there is a link to an archived EJ thread with the blizzlike numbers: https://github.com/SunwellTracker/issues/issues/1528

Link to the archived post: http://web.archive.org/web/20091108152029/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_ptr/

Seems like the proc chance was 20% with no internal gcd.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, this is now fixed and will be corrected after the next maintenance.
