### ISSUE TITLE
Mangle Debuff Not Working

### ISSUE THREAD

**Issue by ArcticDuude** [dalaranwow/issue-tracker#72]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: Mangle (Cat) and Mangle (Bear) do not increase the amount of bleed damage taken by enemies.

**Expected behaviour**: Mangle (Cat) and Mangle (Bear) should increase the bleed damage taken by enemies by 30%.

**Steps to reproduce the problem**:

1. Apply any bleed (rake, rend, piercing shots, etc) and record the amount of damage dealt.
2. After letting the bleed wear off, apply Mangle (Cat) or Mangle (Bear) (both were tested).
3. Repeat Step 1. The damage should be 30% greater, but it is not.

**Include proofs**

1. Rake was applied and dealt 529 damage each tick.
![image](https://github.com/dalaranwow/issue-tracker/assets/133639754/b722e1a2-9165-4625-b10a-ec835030d0ba)
2. Mangle (Cat) was applied after letting Rake wear off.
![image](https://github.com/dalaranwow/issue-tracker/assets/133639754/adcf2955-efe2-407e-9928-dc2584e61f71)
3. Rake was now applied and continued to deal 529 damage each tick.
![image](https://github.com/dalaranwow/issue-tracker/assets/133639754/40bf90e0-0fdc-4ec9-98c3-0d92b14fa0ab)

**Include the ID for the gameobjects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, achievements, skills**

Mangle (Cat) (rank 5) Spell ID: 48566
Mangle (Bear) (rank 5) Spell ID: 48564
Rake (rank 7) Spell ID: 48574
Rip (rank 9) Spell ID: 49800
Lacerate (rank 3) Spell ID: 48568
Shred (rank 9) Spell ID: 48572
Maul (rank 10) Spell ID: 48480
Pounce Bleed (rank 5) Spell ID: 49804
Rend (rank 10) Spell ID: 47465
Deep Wounds (rank 3) Spell ID: 12867
Piercing Shots (rank 3) Spell ID: 53238
Rupture (rank 9) Spell ID: 48672
Garrote (rank 10) Spell ID: 48676

There are likely other bleed effects (such as all the lower ranks of these abilities) that I haven't listed here, but these are the main ones.

**Include Screenshots if you have any, please**

**Comment by cyrilbrugman** [comment]
This would be great now that torches are no longer usable

**Comment by crittycat-dalaran** [comment]
This would be great especially now that the torches are gone

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the heads up, this has been fixed and it will be deployed with the next scheduled maintenance.
