### ISSUE TITLE
Items proccing Clearcasting making Cat Druids ridiculously overpowered

### ISSUE THREAD

**Issue by blahxd** [dalaranwow/issue-tracker#76]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: Items proccing Clearcasting making Cat Druids ridiculously overpowered

**Expected behaviour**: Fix the CC bug, or remove the items

**Steps to reproduce the problem**:

1. Cat Druids can macro Juggling Torches or use items like Stormchops to give constant Clearcasting procs which pretty much gives them infinite energy. 5.6k Cats should not be doing 18k DPS single target. This has been a well known issue since Algalon, I'm surprised this hasn't been fixed yet.
2. I'm sure the items (there are probably more than those two, but those are the most common) that proc Clearcasting can be easily removed as they're not really needed for anything
3. 

**Include proofs**

You can research about the corect behaviour on several sites like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/ or similars.
Issues without proofs may be closed or put on hold until evidence is provided.

**Include the ID for the gameobjects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, achievements, skills**

You can find this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots if you have any, please**

**Comment by Srirachaaz** [comment]
Hopefully they fix the Mangle debuff not increasing bleed damage before they fix this.

**Comment by blahxd** [comment]
> 

True, that also needs to be fixed.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the heads up, this and the mangle issue have been fixed and they will be deployed with the next scheduled maintenance.

**Comment by blahxd** [comment]
> Hello there,
> 
> Thank you for the heads up, this and the mangle issue have been fixed and they will be deployed with the next scheduled maintenance.

Great news. One more thing: The Albino Snake pet can also proc Omen of Clarity (clearcasting) when being spammed. It also tends to lower FPS for some people that game on older computers
