### ISSUE TITLE
Hunter trainer bug

### ISSUE THREAD

**Issue by Splat86** [dalaranwow/issue-tracker#8]
[//]: # (***************************************************************)
[//]: # (**  Please, in order to create a report, fill this template  **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail, please.
When going to the hunter trainer, in this case, if i pick an ability/skill/spell to train that's below the first one, after a few seconds it resets and it goes back to automatically select the first on the list without me doing anything, it does that every time. I have reset the UI, i also uninstalled all the addons and stated the game again and the same issue takes place. Finally, i tried to log in to another private server i used to play on and it works without any issues.

**Expected behaviour**: Tell us what should happen instead.
The expected behavior here is that when we are at a class trainer, no matter which skill we want to train once we select a skill it stays selected, it doesn't automatically switch back to the top of the list. It's extremely annoying having this happening because i have to be super quick picking what i want to train
**Steps to reproduce the problem**:

1. Go to a trainer (hunter trainer in this case)
2. Select a skill/ability/spell that it's not the first one in the list
3. After a few seconds the selection we made automatically resets to the one that's first in the list

**Include proofs**

You can research about the corect behaviour on several sites like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/ or similars.
Issues without proofs may be closed or put on hold until evidence is provided.

**Include the ID for the gameobjects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, achievements, skills**

You can find this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots if you have any, please**
![WoWScrnShot_082122_224807](https://user-images.githubusercontent.com/111729962/185857682-14395552-bec2-41de-a86c-70181f9ed105.jpg)

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report. It doesn't sound like server side issue. I have done some quick checks just in case and couldn't reproduce it. Try to delete your client's cache, disable all addons and even try on different trainers, please.

**Comment by slicplaya** [comment]
I actually have had this happen myself. After deleing cache, and WTF folders. It's like every few seconds it'll tick back to the top choice.
